### ISSUE TITLE
USN C Sharp

### ISSUE THREAD

**Issue by Brakistad** [adrianstrom/USN-ControlSystem-NI-MS#1]
Hello good sir. USN have been using C Sharp for the loongest time. Remember to keep up to date with more open-source languages and platforms to stay strong in the industry today. 
Some suggestions may be;
- C++
- Python
- Golang
- Java
- Javascript / Typescript
Stay sharp buddy, just not to sharp... hehe

**Comment by adrianstrom** [comment]
Hello and thank you for your interest Brakistad. I made a life changing decision when I started to program in C Sharp. And it truly has changed my life forever. I can now C Sharp, and the clarity has been everchanging. I believe I can find God deep in the open sourceness of C Sharp. 

Therefore, I need to fullfill my objective of finding God deep in the code of C Sharp. I will not go a different path. The devil lies in Python I've heard and it's spreading like cancer.

I shall offer you my salvation, take my hand. Join my objective of finding God in C# @Brakistad.

From yours faithfully,

**Comment by Brakistad** [comment]
Good sir, your purpose sounds truly noble and holy. I too, I must admit, have wanted to C Sharp. Yet i can only C PP. This is unfortunate. But my travels have taken far and wide. And i have experienced the bliss of efficiency when i C PP. I only wish your holy practice would be less sharp, and more pp.
Nevertheless, I have recently been on the Go. And after months of PP, it was refreshing to Go for efficiency without all the compatability worries.

It is my wish that you open the source of your heart, and accept that there is a rich variety of GOds.
All with their own churches and bishops.

Stay strong faithful one, belive, hope
Best regards from yours truly XOXO
